### ISSUE TITLE
ERROR: 0:1686: 'OUT' : failed to expand macro

### ISSUE THREAD

**Issue by Atlis** [Piraxus/Skybolt#13]
Hi Matthew,

Here is a small extract of errors I now encounter (they are all similar) :
``` bash
[2022-06-10 10:27:26.411027] [0x00000c94] [error]   FRAGMENT glCompileShader "Shaders/Ocean.frag" FAILED
[2022-06-10 10:27:26.411027] [0x00000c94] [error]   FRAGMENT Shader "Shaders/Ocean.frag" infolog:
ERROR: 0:1686: 'OUT' : failed to expand macro
[2022-06-10 10:27:26.426685] [0x00000c94] [error]   VERTEX glCompileShader "Shaders/OceanProjected.vert" FAILED
[2022-06-10 10:27:26.426685] [0x00000c94] [error]   VERTEX Shader "Shaders/OceanProjected.vert" infolog:
ERROR: 0:1737: 'OUT' : failed to expand macro
```

What could be causing this?

Thanks.

**Comment by Atlis** [comment]
This is what I see:
![Untitled](https://user-images.githubusercontent.com/6990801/173089462-e2a734a5-7319-4584-a7f9-45cccb414d1c.png)

**Comment by matthew-reid** [comment]
The atmospheric shader defines a macro ```OUT(x)``` which should expand to ```x```, but on your system it's failing to expand. I suspect it may be graphics driver related. What graphics card are you using?

**Comment by Atlis** [comment]
Its a Nvidia Geforce GTX 1050 Ti with driver version 511.69.

**Comment by matthew-reid** [comment]
I'm using a similar card: Geforce GTX 1070 with driver version 516.01. Can you please post the full error log?

**Comment by matthew-reid** [comment]
I have a guess as to the problem. I just pushed a new branch which might possibly fix it, can you please try the ```macroExpansionFixAttempt``` branch.

**Comment by Atlis** [comment]
Using:
* Boost 1.74 compiled and installed with the following commands (I did not manage to make it work with 1.67 but I may give it another try):
  ``` bash
   b2 release debug threading=multi --build-type=complete --toolset=msvc address-model=64 stage
   b2 install
  ```
* OSG 3.6.5 from [Windows Binaries provided by OBJEXX Engineering](https://objexx.com/OpenSceneGraph.html)
* SkyboltDependenciesHeaderOnly with tag: Skybolt-1.2.0 (since `master` is not working)

Here is the output:

``` bash
(pytorch111_cuda113_v13) C:\Users\xxxxx\Documents\Skybolt\build\bin\Release>MinimalApp.exe
[2022-06-10 11:32:24.705931] [0x000032a8] [info]    No --settingsFile program argument specified. Using default settings file location: '"C:\\Users\\xxxxx\\AppData\\Local\\Skybolt\\Settings.json"'
[2022-06-10 11:32:24.705931] [0x000032a8] [info]    Reading settings file '"C:\\Users\\xxxxx\\AppData\\Local\\Skybolt\\Settings.json"'
[2022-06-10 11:32:24.705931] [0x000032a8] [info]    12 CPU cores detected.  Creating 11 background threads.
[2022-06-10 11:32:24.705931] [0x000032a8] [info]    Registered asset package: Core
[2022-06-10 11:32:24.705931] [0x000032a8] [info]    Registered asset package: Globe
[2022-06-10 11:32:24.705931] [0x000032a8] [info]    Registered asset package: Movers
[2022-06-10 11:32:27.081524] [0x000032a8] [info]
[2022-06-10 11:32:27.081524] [0x000032a8] [error]   FRAGMENT glCompileShader "Shaders/Ocean.frag" FAILED
[2022-06-10 11:32:27.081524] [0x000032a8] [error]   FRAGMENT Shader "Shaders/Ocean.frag" infolog:
ERROR: 0:1686: 'OUT' : failed to expand macro
[2022-06-10 11:32:27.089580] [0x000032a8] [error]   VERTEX glCompileShader "Shaders/OceanProjected.vert" FAILED
[2022-06-10 11:32:27.089580] [0x000032a8] [error]   VERTEX Shader "Shaders/OceanProjected.vert" infolog:
ERROR: 0:1737: 'OUT' : failed to expand macro
[2022-06-10 11:32:27.115252] [0x000032a8] [error]   FRAGMENT glCompileShader "Shaders/VolumeClouds.frag" FAILED
[2022-06-10 11:32:27.115252] [0x000032a8] [error]   FRAGMENT Shader "Shaders/VolumeClouds.frag" infolog:
ERROR: 0:1684: 'OUT' : failed to expand macro
[2022-06-10 11:32:27.130838] [0x000032a8] [error]   FRAGMENT glCompileShader "Shaders/Planet.frag" FAILED
[2022-06-10 11:32:27.130838] [0x000032a8] [error]   FRAGMENT Shader "Shaders/Planet.frag" infolog:
ERROR: 0:1686: 'OUT' : failed to expand macro
[2022-06-10 11:32:27.146492] [0x000032a8] [error]   VERTEX glCompileShader "Shaders/Planet.vert" FAILED
[2022-06-10 11:32:27.146492] [0x000032a8] [error]   VERTEX Shader "Shaders/Planet.vert" infolog:
ERROR: 0:1685: 'OUT' : failed to expand macro
[2022-06-10 11:32:28.963605] [0x000032a8] [error]   FRAGMENT glCompileShader "Shaders/VolumeClouds.frag" FAILED
[2022-06-10 11:32:28.963605] [0x000032a8] [error]   FRAGMENT Shader "Shaders/VolumeClouds.frag" infolog:
ERROR: 2:1684: 'OUT' : failed to expand macro
[2022-06-10 11:32:29.113229] [0x000032a8] [error]   FRAGMENT glCompileShader "Shaders/Ocean.frag" FAILED
[2022-06-10 11:32:29.113229] [0x000032a8] [error]   FRAGMENT Shader "Shaders/Ocean.frag" infolog:
ERROR: 2:1686: 'OUT' : failed to expand macro
[2022-06-10 11:32:29.113229] [0x000032a8] [error]   VERTEX glCompileShader "Shaders/OceanProjected.vert" FAILED
[2022-06-10 11:32:29.113229] [0x000032a8] [error]   VERTEX Shader "Shaders/OceanProjected.vert" infolog:
ERROR: 2:1737: 'OUT' : failed to expand macro
```

**Comment by Atlis** [comment]
Yeah! It fixed the error.
![Untitled](https://user-images.githubusercontent.com/6990801/173108175-93fbe09f-a682-4362-9134-6ad75f18eda7.png)
I will close the issue. Thank you very much for your help!

However, I still don't see the terrain. What is missing? And I would not know how to install NLCD Land Cover or Seattle map features either.

I have the following `Settings.json`:
``` json
{
    "tileApiKeys": {
        "mapbox": "pk.eyJ1IjoiYXRsaXMiLCJhIjoiY2w0OGw*****************"
    }
}
```

**Comment by matthew-reid** [comment]
Glad that fixed it.

To install NLCD and Seattle you need to extract those archives and put the "NLCDLandCover" and "Seattle" folders in a directory contained in the SKYBOLT_ASSETS_PATH environment variable. Skybolt will load all asset packages on that path, and for each loaded package you'll see a `Registered asset package` message in the log.

Your `Settings.json` file looks correct. Are there any errors in the log? If not it might be silently failing to download the tiles from the internet, in which case I'll add better error logging to help diagnose the problem.

**Comment by matthew-reid** [comment]
I just pushed a [commit ](https://github.com/Piraxus/Skybolt/commit/f475a60c15a73fd3c3dcb5af7545785eabfe13c1) to master which adds some error checking for terrain tile loads. You should get a log message if the tiles could not be accessed.
